### ISSUE TITLE
ChurchRota not working on PHP 7

### ISSUE THREAD

**Issue by AlexanderVermeulen** [Little-Ben/ChurchRota#10]
I tried to install ChurchRota for my church. After putting al files on the webserver and creating a database, i got an 500 errror on starting the install.php. Some searching learned me that mysql is not available on PHP version 7 anymore. 
I found a fix by using this: https://github.com/rubo77/php-mysql-fix
but would be nice to get it up and running again

**Comment by Little-Ben** [comment]
Since some years we are using an alternative (paid) solution in our church, so I am not actively using or working on ChurchRota anymore. The problem is surely the dropped backward compability in php 7. Might also affect other (non-mysql) functions. 

I will have a look into it, but I am not sure how fast or even if there will be a working solution.
If you have working code fixes, feel free to send pull requests.

**Comment by AlexanderVermeulen** [comment]
I am not that familiar with GIT yet. But i will try to send you a pull request.
When you are not updating the project anymore, can i fork it and start a new project from that point?
I want use it for my church. For Covid-19 we have to prepare a schedule who can attend the service in the church building and who should attend online. I want to use your project as starting point, translate it to dutch and change some functionalities to support "member assignments per service" .

**Comment by Little-Ben** [comment]
This topic is further disussed in pull request  #11

**Comment by Little-Ben** [comment]
I am gald if you like to contribute to the project, so it goes on.
Since I do not activly use or maintain the project, what about you to take over the project as maintainer?
As I have taken over from original implementor David Bunce.

So version could be:
v1.x David Bounce
v2.x Benjamin Schmitt
v3.x Alexander Vermeulen

It would be your decissions to what the projects develops in future.
What do you think?

**Comment by Little-Ben** [comment]
On suggestion, because I do notr know wheter anybody is using ChurchRota at teh moment.
If you introduce translation, maybe you could make it switchable, so that at least English and Durch will be present.
Depending on your chosen way of internationalization, I might contribute a language file for German.

**Comment by Little-Ben** [comment]
solved with merging pull request #11

**Comment by AlexanderVermeulen** [comment]
No thanks Benjamin. I realized i needed to change a lot to make it fit for my church.
So i started something new.
